#!/usr/bin/env python3
"""Generate ducet_data.c from a pinned Unicode allkeys.txt (DUCET).

The Default Unicode Collation Element Table maps a code point (or a short
sequence, for contractions) to a list of collation elements, each a
(primary, secondary, tertiary) weight triple. UTS #10's Unicode Collation
Algorithm turns those into a multi-level sort key.

We emit a compact C table rather than an Aether const array: 34k entries with
variable-length CE lists compile far faster as C (compiled once and cached like
utf8proc), and the lookup is a tight binary search. The Aether `collate` module
calls into it via the C wrapper.

Layout emitted (all in ducet_data.c):
  - ducet_ce[]        : flat array of uint32 collation elements, packed as
                        (primary<<16 not used) — we store 3 x uint16 per CE in
                        three parallel-free struct: {uint16 p; uint16 s; uint16 t;}
  - ducet_single[]    : sorted-by-codepoint entries {uint32 cp; uint32 ce_off;
                        uint16 ce_len;} for binary search
  - ducet_contract[]  : multi-codepoint entries {uint32 cp0; uint32 cp1;
                        uint32 ce_off; uint16 ce_len;} sorted by (cp0,cp1);
                        only length-2 contractions are kept (covers the DUCET's
                        real contractions used by Latin/Cyrillic/Greek locales).

Regenerate:
    python3 gen_ducet.py allkeys.txt > ducet_data.c

Do not edit ducet_data.c by hand.
"""
import sys
import re

CE_RE = re.compile(r"\[[.*]([0-9A-Fa-f]{4,5})\.([0-9A-Fa-f]{4})\.([0-9A-Fa-f]{4})\]")


def parse(path):
    singles = []      # (cp, [(p,s,t),...])
    contracts = []    # (cp0, cp1, [(p,s,t),...])
    version = "unknown"
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("@version"):
                version = line.split()[1]
                continue
            # strip comments
            hash_i = line.find("#")
            if hash_i != -1:
                line = line[:hash_i]
            line = line.strip()
            if not line or line.startswith("@"):
                continue
            if ";" not in line:
                continue
            cps_str, weights_str = line.split(";", 1)
            cps = cps_str.split()
            if not cps:
                continue
            try:
                cp_list = [int(c, 16) for c in cps]
            except ValueError:
                continue
            ces = []
            for m in CE_RE.finditer(weights_str):
                p = int(m.group(1), 16)
                s = int(m.group(2), 16)
                t = int(m.group(3), 16)
                # primary can be 5 hex digits (>0xFFFF) for a few CJK; DUCET
                # single-CE primaries used by tailored locales fit in 16 bits.
                # Clamp/skip entries whose primary overflows uint16 — those are
                # implicit-weight CJK ranges we approximate at runtime.
                if p > 0xFFFF:
                    ces = None
                    break
                ces.append((p, s, t))
            if ces is None or not ces:
                continue
            if len(cp_list) == 1:
                singles.append((cp_list[0], ces))
            elif len(cp_list) == 2:
                contracts.append((cp_list[0], cp_list[1], ces))
            # ignore len>=3 contractions (vanishingly rare; approximated by
            # falling back to per-codepoint lookup)
    return version, singles, contracts


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: gen_ducet.py allkeys.txt > ducet_data.c\n")
        sys.exit(2)
    version, singles, contracts = parse(sys.argv[1])
    singles.sort(key=lambda e: e[0])
    contracts.sort(key=lambda e: (e[0], e[1]))

    # Flatten CEs into one array; record offsets.
    ce_flat = []       # list of (p,s,t)
    def emit_ces(ces):
        off = len(ce_flat)
        ce_flat.extend(ces)
        return off, len(ces)

    single_rows = []
    for cp, ces in singles:
        off, n = emit_ces(ces)
        single_rows.append((cp, off, n))

    contract_rows = []
    for cp0, cp1, ces in contracts:
        off, n = emit_ces(ces)
        contract_rows.append((cp0, cp1, off, n))

    out = sys.stdout.write
    out("/* ducet_data.c — GENERATED by gen_ducet.py from allkeys.txt. DO NOT EDIT. */\n")
    out("/* Default Unicode Collation Element Table (DUCET), UCA version %s. */\n" % version)
    out("/* Copyright (c) Unicode, Inc.; used under the Unicode Terms of Use. */\n")
    out("/* See contrib/i18n/ducet/NOTICE. */\n\n")
    out('#include "ducet.h"\n\n')

    out("const int aether_ducet_ce_count = %d;\n" % len(ce_flat))
    out("const AetherCE aether_ducet_ce[] = {\n")
    for (p, s, t) in ce_flat:
        out("  {0x%04X,0x%04X,0x%04X},\n" % (p, s, t))
    out("};\n\n")

    out("const int aether_ducet_single_count = %d;\n" % len(single_rows))
    out("const AetherDucetSingle aether_ducet_single[] = {\n")
    for (cp, off, n) in single_rows:
        out("  {0x%06X,%d,%d},\n" % (cp, off, n))
    out("};\n\n")

    out("const int aether_ducet_contract_count = %d;\n" % len(contract_rows))
    out("const AetherDucetContract aether_ducet_contract[] = {\n")
    for (cp0, cp1, off, n) in contract_rows:
        out("  {0x%06X,0x%06X,%d,%d},\n" % (cp0, cp1, off, n))
    out("};\n")


if __name__ == "__main__":
    main()
