/* Compiled module artifacts (`.aea`, issue #1746). See aether_aea.h for the
 * layout and for what an artifact promises. */
#include "aether_aea.h"

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by the Makefile from the lexer, parser and AST sources: any edit
 * to how text becomes an AST changes it, so an artifact made by a different
 * front end is never decoded by this one. */
#include "aether_frontend_id.h"

/* An AST deeper than this is not something the parser produces (its own
 * nesting limit is 512); refusing it keeps a damaged file from exhausting
 * the stack. */
#define AEA_MAX_DEPTH 10000

/* A front end built without the generated fingerprint (a hand-rolled
 * compile) reports this, and neither makes nor accepts artifacts. */
#define AEA_UNKNOWN_FRONTEND "unknown"

uint64_t aea_hash(const char* data, size_t len) {
    uint64_t h = 14695981039346656037ULL;   /* FNV-1a 64 offset basis */
    for (size_t i = 0; i < len; i++) {
        h ^= (unsigned char)data[i];
        h *= 1099511628211ULL;
    }
    return h;
}

const char* aea_frontend_id(void) {
#ifdef AETHER_FRONTEND_ID
    return AETHER_FRONTEND_ID;
#else
    return AEA_UNKNOWN_FRONTEND;
#endif
}

/* ------------------------------------------------------------------ */
/* Encoding                                                            */
/* ------------------------------------------------------------------ */

typedef struct {
    char* data;
    size_t len;
    size_t cap;
    int failed;
} Buf;

static void buf_put(Buf* b, const char* s, size_t n) {
    if (b->failed) return;
    if (b->len + n + 1 > b->cap) {
        size_t cap = b->cap ? b->cap : 4096;
        while (b->len + n + 1 > cap) cap *= 2;
        char* d = realloc(b->data, cap);
        if (!d) { b->failed = 1; return; }
        b->data = d;
        b->cap = cap;
    }
    memcpy(b->data + b->len, s, n);
    b->len += n;
    b->data[b->len] = '\0';
}

static void buf_str(Buf* b, const char* s) { buf_put(b, s, strlen(s)); }

static void buf_int(Buf* b, long long v) {
    char tmp[32];
    int n = snprintf(tmp, sizeof(tmp), " %lld", v);
    buf_put(b, tmp, (size_t)n);
}

/* ` ~` for NULL, else ` <len>:<bytes>`, so any byte can appear in a value. */
static void buf_text(Buf* b, const char* s) {
    if (!s) { buf_put(b, " ~", 2); return; }
    char tmp[32];
    size_t n = strlen(s);
    int k = snprintf(tmp, sizeof(tmp), " %zu:", n);
    buf_put(b, tmp, (size_t)k);
    buf_put(b, s, n);
}

static int encode_type(Buf* b, const Type* t, const char** err) {
    if (!t) { buf_put(b, " ~", 2); return 1; }
    if (t->compound_node) {
        /* Set by the type checker only; a parse never produces it. */
        *err = "a type carries a type-checker back-pointer (not a fresh parse)";
        return 0;
    }
    buf_put(b, " T", 2);
    buf_int(b, t->kind);
    buf_int(b, t->array_size);
    buf_text(b, t->struct_name);
    buf_text(b, t->c_alias);
    buf_text(b, t->distinct_name);
    buf_text(b, t->index_enum_name);
    if (!encode_type(b, t->element_type, err)) return 0;
    int tuples = (t->tuple_types && t->tuple_count > 0) ? t->tuple_count : 0;
    buf_int(b, tuples);
    for (int i = 0; i < tuples; i++)
        if (!encode_type(b, t->tuple_types[i], err)) return 0;
    buf_int(b, (tuples > 0 && t->tuple_heap_flags) ? 1 : 0);
    if (tuples > 0 && t->tuple_heap_flags)
        for (int i = 0; i < tuples; i++) buf_int(b, t->tuple_heap_flags[i]);
    int params = (t->param_types && t->param_count > 0) ? t->param_count : 0;
    buf_int(b, params);
    for (int i = 0; i < params; i++)
        if (!encode_type(b, t->param_types[i], err)) return 0;
    if (!encode_type(b, t->return_type, err)) return 0;
    buf_int(b, t->is_fnptr);
    buf_int(b, t->is_result);
    return 1;
}

static int encode_node(Buf* b, const ASTNode* n, const char* source_file,
                       int depth, const char** err) {
    if (depth > AEA_MAX_DEPTH) { *err = "the AST is deeper than an artifact may hold"; return 0; }
    if (n->is_imported || n->warned) {
        *err = "the AST has been merged or analysed (not a fresh parse)";
        return 0;
    }
    /* The whole module must come from one file: the consumer re-stamps every
     * node with the one path it resolved. */
    if (n->source_file && (!source_file || strcmp(n->source_file, source_file) != 0)) {
        *err = "the AST mixes nodes from more than one source file";
        return 0;
    }
    buf_put(b, "N", 1);
    buf_int(b, n->type);
    buf_int(b, n->line);
    buf_int(b, n->column);
    buf_int(b, n->bit_width);
    buf_int(b, n->bit_lo);
    buf_int(b, n->bit_hi);
    buf_int(b, n->type_inferred);
    buf_text(b, n->value);
    buf_text(b, n->annotation);
    if (!encode_type(b, n->node_type, err)) return 0;
    buf_int(b, n->child_count);
    buf_put(b, "\n", 1);
    for (int i = 0; i < n->child_count; i++) {
        if (!n->children[i]) { *err = "the AST has a null child"; return 0; }
        if (!encode_node(b, n->children[i], source_file, depth + 1, err)) return 0;
    }
    return 1;
}

/* Values go on one header line each, so they may not hold whitespace. */
static int header_safe(const char* s) {
    if (!s || !*s) return 0;
    for (const char* p = s; *p; p++)
        if (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') return 0;
    return 1;
}

static int source_rel_ok(const char* rel) {
    if (!header_safe(rel)) return 0;
    if (rel[0] == '/' || strchr(rel, '\\') || strchr(rel, ':')) return 0;
    /* No `..` segment: the path names a file inside the install root. */
    const char* p = rel;
    while (*p) {
        const char* seg_end = strchr(p, '/');
        size_t seg = seg_end ? (size_t)(seg_end - p) : strlen(p);
        if (seg == 0 || (seg == 2 && p[0] == '.' && p[1] == '.') ||
            (seg == 1 && p[0] == '.')) return 0;
        if (!seg_end) break;
        p = seg_end + 1;
    }
    return 1;
}

char* aea_encode(const ASTNode* ast, const AeaProducer* pr,
                 size_t* out_len, const char** err) {
    static const char* unused;
    if (!err) err = &unused;
    *err = NULL;
    if (!ast || !pr || !out_len) { *err = "nothing to encode"; return NULL; }
    if (!header_safe(pr->aether_version)) { *err = "no usable compiler version"; return NULL; }
    if (!header_safe(pr->frontend_id) || strcmp(pr->frontend_id, AEA_UNKNOWN_FRONTEND) == 0) {
        *err = "this compiler was built without a front-end fingerprint";
        return NULL;
    }
    if (!source_rel_ok(pr->source_rel)) {
        *err = "the source path must be install-relative, like std/x/module.ae";
        return NULL;
    }
    if (!pr->source_text) { *err = "no source text to hash"; return NULL; }
    for (int i = 0; i < pr->define_count; i++) {
        if (!header_safe(pr->defines[i].name)) { *err = "a build symbol name is unusable"; return NULL; }
    }

    /* The payload is stamped-path agnostic: nodes carry the producer's path
     * only as a same-file check, never into the artifact. */
    const char* stamped = ast->source_file;
    Buf payload = {0};
    if (!encode_node(&payload, ast, stamped, 0, err)) { free(payload.data); return NULL; }
    if (payload.failed) { free(payload.data); *err = "out of memory"; return NULL; }

    char* module = aea_module_name_for(pr->source_rel);
    Buf out = {0};
    char line[256];
    snprintf(line, sizeof(line), "AEA %d\n", AEA_FORMAT_VERSION);
    buf_str(&out, line);
    buf_str(&out, "aether_version "); buf_str(&out, pr->aether_version); buf_str(&out, "\n");
    buf_str(&out, "frontend ");       buf_str(&out, pr->frontend_id);    buf_str(&out, "\n");
    buf_str(&out, "module ");         buf_str(&out, module ? module : "?"); buf_str(&out, "\n");
    buf_str(&out, "source ");         buf_str(&out, pr->source_rel);     buf_str(&out, "\n");
    snprintf(line, sizeof(line), "source_hash %016" PRIx64 "\n",
             aea_hash(pr->source_text, pr->source_len));
    buf_str(&out, line);
    for (int i = 0; i < pr->define_count; i++) {
        buf_str(&out, "define ");
        buf_str(&out, pr->defines[i].name);
        buf_str(&out, pr->defines[i].value ? " 1\n" : " 0\n");
    }
    snprintf(line, sizeof(line), "payload_hash %016" PRIx64 "\n",
             aea_hash(payload.data ? payload.data : "", payload.len));
    buf_str(&out, line);
    snprintf(line, sizeof(line), "payload %zu\n", payload.len);
    buf_str(&out, line);
    if (payload.len) buf_put(&out, payload.data, payload.len);
    free(payload.data);
    free(module);
    if (out.failed) { free(out.data); *err = "out of memory"; return NULL; }
    *out_len = out.len;
    return out.data;
}

/* ------------------------------------------------------------------ */
/* Decoding                                                            */
/* ------------------------------------------------------------------ */

typedef struct {
    const char* p;
    const char* end;
    int bad;
} Cursor;

static int cur_char(Cursor* c, char want) {
    if (c->bad || c->p >= c->end || *c->p != want) { c->bad = 1; return 0; }
    c->p++;
    return 1;
}

static long long cur_int(Cursor* c) {
    if (!cur_char(c, ' ')) return 0;
    int neg = 0;
    if (c->p < c->end && *c->p == '-') { neg = 1; c->p++; }
    if (c->p >= c->end || *c->p < '0' || *c->p > '9') { c->bad = 1; return 0; }
    long long v = 0;
    while (c->p < c->end && *c->p >= '0' && *c->p <= '9') {
        if (v > (long long)(INT32_MAX) * 10) { c->bad = 1; return 0; }
        v = v * 10 + (*c->p - '0');
        c->p++;
    }
    if (v > INT32_MAX) { c->bad = 1; return 0; }
    return neg ? -v : v;
}

/* An int field, rejected when negative where the codec never writes one. */
static int cur_count(Cursor* c) {
    long long v = cur_int(c);
    if (v < 0) c->bad = 1;
    return (int)v;
}

static char* cur_text(Cursor* c) {
    if (!cur_char(c, ' ')) return NULL;
    if (c->p < c->end && *c->p == '~') { c->p++; return NULL; }
    size_t n = 0;
    if (c->p >= c->end || *c->p < '0' || *c->p > '9') { c->bad = 1; return NULL; }
    while (c->p < c->end && *c->p >= '0' && *c->p <= '9') {
        n = n * 10 + (size_t)(*c->p - '0');
        if (n > (size_t)(c->end - c->p)) { c->bad = 1; return NULL; }
        c->p++;
    }
    if (!cur_char(c, ':')) return NULL;
    if ((size_t)(c->end - c->p) < n) { c->bad = 1; return NULL; }
    char* s = malloc(n + 1);
    if (!s) { c->bad = 1; return NULL; }
    memcpy(s, c->p, n);
    s[n] = '\0';
    c->p += n;
    return s;
}

static Type* decode_type(Cursor* c, int depth) {
    if (!cur_char(c, ' ')) return NULL;
    if (c->p < c->end && *c->p == '~') { c->p++; return NULL; }
    if (!cur_char(c, 'T')) return NULL;
    if (depth > AEA_MAX_DEPTH) { c->bad = 1; return NULL; }
    Type* t = create_type((TypeKind)cur_count(c));
    t->array_size = (int)cur_int(c);
    t->struct_name = cur_text(c);
    t->c_alias = cur_text(c);
    t->distinct_name = cur_text(c);
    t->index_enum_name = cur_text(c);
    t->element_type = decode_type(c, depth + 1);
    int tuples = cur_count(c);
    if (!c->bad && tuples > 0) {
        if (tuples > (int)(c->end - c->p)) { c->bad = 1; return t; }
        t->tuple_types = calloc((size_t)tuples, sizeof(Type*));
        if (!t->tuple_types) { c->bad = 1; return t; }
        t->tuple_count = tuples;
        for (int i = 0; i < tuples && !c->bad; i++) t->tuple_types[i] = decode_type(c, depth + 1);
    }
    int has_flags = cur_count(c);
    if (!c->bad && has_flags) {
        if (tuples <= 0) { c->bad = 1; return t; }
        t->tuple_heap_flags = calloc((size_t)tuples, sizeof(int));
        if (!t->tuple_heap_flags) { c->bad = 1; return t; }
        for (int i = 0; i < tuples && !c->bad; i++) t->tuple_heap_flags[i] = (int)cur_int(c);
    }
    int params = cur_count(c);
    if (!c->bad && params > 0) {
        if (params > (int)(c->end - c->p)) { c->bad = 1; return t; }
        t->param_types = calloc((size_t)params, sizeof(Type*));
        if (!t->param_types) { c->bad = 1; return t; }
        t->param_count = params;
        for (int i = 0; i < params && !c->bad; i++) t->param_types[i] = decode_type(c, depth + 1);
    }
    t->return_type = decode_type(c, depth + 1);
    t->is_fnptr = (int)cur_int(c);
    t->is_result = (int)cur_int(c);
    return t;
}

static ASTNode* decode_node(Cursor* c, int depth) {
    if (depth > AEA_MAX_DEPTH || !cur_char(c, 'N')) { c->bad = 1; return NULL; }
    int type = cur_count(c);
    int line = (int)cur_int(c);
    int column = (int)cur_int(c);
    if (c->bad) return NULL;
    ASTNode* n = create_ast_node((ASTNodeType)type, NULL, line, column);
    n->bit_width = (int)cur_int(c);
    n->bit_lo = (int)cur_int(c);
    n->bit_hi = (int)cur_int(c);
    n->type_inferred = (int)cur_int(c);
    n->value = cur_text(c);
    n->annotation = cur_text(c);
    n->node_type = decode_type(c, depth + 1);
    int children = cur_count(c);
    cur_char(c, '\n');
    /* Every child costs at least a few bytes, so a count the rest of the
     * payload cannot hold is damage, not a big module. */
    if (!c->bad && children > (int)(c->end - c->p)) c->bad = 1;
    for (int i = 0; i < children && !c->bad; i++) {
        ASTNode* child = decode_node(c, depth + 1);
        if (child) add_child(n, child);
    }
    return n;
}

/* Reads one `key value` header line into key/value (NUL-terminated copies,
 * truncated to the buffers). Returns 0 at a malformed or missing line. */
static int header_line(Cursor* c, char* key, size_t kcap, char* val, size_t vcap) {
    const char* nl = memchr(c->p, '\n', (size_t)(c->end - c->p));
    if (!nl) return 0;
    const char* sp = memchr(c->p, ' ', (size_t)(nl - c->p));
    if (!sp) return 0;
    size_t kn = (size_t)(sp - c->p), vn = (size_t)(nl - sp - 1);
    if (kn == 0 || kn >= kcap || vn >= vcap) return 0;
    memcpy(key, c->p, kn); key[kn] = '\0';
    memcpy(val, sp + 1, vn); val[vn] = '\0';
    c->p = nl + 1;
    return 1;
}

static int parse_hex64(const char* s, uint64_t* out) {
    if (strlen(s) != 16) return 0;
    uint64_t v = 0;
    for (const char* p = s; *p; p++) {
        int d;
        if (*p >= '0' && *p <= '9') d = *p - '0';
        else if (*p >= 'a' && *p <= 'f') d = *p - 'a' + 10;
        else return 0;
        v = (v << 4) | (uint64_t)d;
    }
    *out = v;
    return 1;
}

ASTNode* aea_decode(const char* data, size_t len, const AeaConsumer* co,
                    const char** why) {
    static const char* unused;
    if (!why) why = &unused;
    *why = NULL;
    if (!data || !co) { *why = "nothing to decode"; return NULL; }

    Cursor c = { data, data + len, 0 };
    char key[64], val[512];
    char magic[32];
    snprintf(magic, sizeof(magic), "%d", AEA_FORMAT_VERSION);
    if (!header_line(&c, key, sizeof(key), val, sizeof(val)) || strcmp(key, "AEA") != 0) {
        *why = "not an artifact";
        return NULL;
    }
    if (strcmp(val, magic) != 0) { *why = "artifact format version differs"; return NULL; }

    int seen_version = 0, seen_frontend = 0, seen_source = 0, seen_hash = 0;
    int seen_payload_hash = 0;
    uint64_t payload_hash = 0;
    const char* fe = co->frontend_id;
    for (;;) {
        if (!header_line(&c, key, sizeof(key), val, sizeof(val))) {
            *why = "artifact header is malformed";
            return NULL;
        }
        if (strcmp(key, "aether_version") == 0) {
            if (!co->aether_version || strcmp(val, co->aether_version) != 0) {
                *why = "built by another compiler version";
                return NULL;
            }
            seen_version = 1;
        } else if (strcmp(key, "frontend") == 0) {
            if (!fe || strcmp(fe, AEA_UNKNOWN_FRONTEND) == 0 || strcmp(val, fe) != 0) {
                *why = "built by another compiler front end";
                return NULL;
            }
            seen_frontend = 1;
        } else if (strcmp(key, "module") == 0) {
            /* Informational: the source path below is what identifies it. */
        } else if (strcmp(key, "source") == 0) {
            if (!co->source_rel || strcmp(val, co->source_rel) != 0) {
                *why = "built from another source file";
                return NULL;
            }
            seen_source = 1;
        } else if (strcmp(key, "source_hash") == 0) {
            uint64_t want;
            if (!parse_hex64(val, &want)) { *why = "artifact header is malformed"; return NULL; }
            if (!co->source_text || want != aea_hash(co->source_text, co->source_len)) {
                *why = "source changed since the artifact was built";
                return NULL;
            }
            seen_hash = 1;
        } else if (strcmp(key, "define") == 0) {
            char* sp = strchr(val, ' ');
            if (!sp || (strcmp(sp + 1, "0") != 0 && strcmp(sp + 1, "1") != 0)) {
                *why = "artifact header is malformed";
                return NULL;
            }
            *sp = '\0';
            int now = co->define_is_set ? (co->define_is_set(val) ? 1 : 0) : 0;
            if (now != (sp[1] == '1')) {
                *why = "a build symbol the module tests is set differently";
                return NULL;
            }
        } else if (strcmp(key, "payload_hash") == 0) {
            if (!parse_hex64(val, &payload_hash)) { *why = "artifact header is malformed"; return NULL; }
            seen_payload_hash = 1;
        } else if (strcmp(key, "payload") == 0) {
            break;
        } else {
            /* A key this reader does not know could change what the payload
             * means; a reader that cannot interpret it must not trust it. */
            *why = "artifact header has a key this compiler does not know";
            return NULL;
        }
    }
    if (!seen_version || !seen_frontend || !seen_source || !seen_hash || !seen_payload_hash) {
        *why = "artifact header is incomplete";
        return NULL;
    }
    char* endp = NULL;
    unsigned long long plen = strtoull(val, &endp, 10);
    if (!endp || *endp || plen != (unsigned long long)(c.end - c.p)) {
        *why = "artifact payload is truncated";
        return NULL;
    }
    if (aea_hash(c.p, (size_t)plen) != payload_hash) {
        *why = "artifact payload is damaged";
        return NULL;
    }
    ASTNode* ast = decode_node(&c, 0);
    if (c.bad || c.p != c.end) {
        free_ast_node(ast);
        *why = "artifact payload is malformed";
        return NULL;
    }
    return ast;
}

/* ------------------------------------------------------------------ */
/* Paths                                                               */
/* ------------------------------------------------------------------ */

static int is_sep(char ch) { return ch == '/' || ch == '\\'; }

/* Finds the last `<sep>share<sep>aether<sep>` in `path`, either separator,
 * and returns the index of its first separator, or -1. */
static long find_install_root(const char* path) {
    static const char* const parts[] = { "share", "aether" };
    long found = -1;
    size_t n = strlen(path);
    for (size_t i = 0; i < n; i++) {
        if (!is_sep(path[i])) continue;
        size_t j = i + 1;
        int ok = 1;
        for (int k = 0; k < 2 && ok; k++) {
            size_t pl = strlen(parts[k]);
            if (strncmp(path + j, parts[k], pl) != 0 || !is_sep(path[j + pl])) ok = 0;
            else j += pl + 1;
        }
        if (ok) found = (long)i;
    }
    return found;
}

char* aea_artifact_path_for(const char* source_path, char** source_rel_out) {
    if (source_rel_out) *source_rel_out = NULL;
    if (!source_path) return NULL;
    long root = find_install_root(source_path);
    if (root < 0) return NULL;
    const char* rel_start = source_path + root + strlen("/share/aether/");
    size_t rel_len = strlen(rel_start);
    static const char ext[] = ".ae";
    if (rel_len <= sizeof(ext) - 1 ||
        strcmp(rel_start + rel_len - (sizeof(ext) - 1), ext) != 0) return NULL;

    char* rel = malloc(rel_len + 1);
    if (!rel) return NULL;
    for (size_t i = 0; i <= rel_len; i++) rel[i] = is_sep(rel_start[i]) ? '/' : rel_start[i];
    if (!source_rel_ok(rel)) { free(rel); return NULL; }

    /* <stem>/module.ae names the module <stem>; any other <stem>.ae keeps
     * its own name. */
    size_t stem_len = rel_len - (sizeof(ext) - 1);
    static const char facade[] = "/module.ae";
    if (rel_len > sizeof(facade) - 1 &&
        strcmp(rel + rel_len - (sizeof(facade) - 1), facade) == 0)
        stem_len = rel_len - (sizeof(facade) - 1);

    static const char lib[] = "/lib/aether/modules/";
    size_t prefix_len = (size_t)root;
    size_t total = prefix_len + (sizeof(lib) - 1) + stem_len + strlen(".aea") + 1;
    char* out = malloc(total);
    if (!out) { free(rel); return NULL; }
    memcpy(out, source_path, prefix_len);
    snprintf(out + prefix_len, total - prefix_len, "%s%.*s.aea", lib, (int)stem_len, rel);
    if (source_rel_out) *source_rel_out = rel;
    else free(rel);
    return out;
}

char* aea_module_name_for(const char* source_rel) {
    if (!source_rel) return NULL;
    size_t n = strlen(source_rel);
    static const char facade[] = "/module.ae";
    if (n > sizeof(facade) - 1 && strcmp(source_rel + n - (sizeof(facade) - 1), facade) == 0)
        n -= sizeof(facade) - 1;
    else if (n > 3 && strcmp(source_rel + n - 3, ".ae") == 0)
        n -= 3;
    char* out = malloc(n + 1);
    if (!out) return NULL;
    for (size_t i = 0; i < n; i++) out[i] = (source_rel[i] == '/') ? '.' : source_rel[i];
    out[n] = '\0';
    return out;
}
